version: "3.1"

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      main:
        ipv4_address: 172.22.0.2

  php-fpm:
    image: php:fpm
    build:
      context: ./php-fpm
      dockerfile: DockerFile
    container_name: php-fpm
    volumes:
      - ../:/var/www/html
    ports:
      - "${PHP_PORT}:9000"
    networks:
      main:
        ipv4_address: 172.22.0.3

  nginx:
    image: nginx:1.18
    container_name: nginx
    volumes:
      - ../:/var/www/html
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ""${WEB_PORT}:80"
    depends_on:
      - 'php-fpm'
    networks:
      main:
        ipv4_address: 172.22.0.4

networks:
  main:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16
          gateway: 172.22.0.1